config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :noms
  end

  resources :noms, only: [] do
    resources :photos
  end

  resources :events

  root 'site#index'
  get '/places' => 'site#places'
  get '/contact' => 'site#contact'
  post '/contact' => 'site#contact'

  get '/login' => 'site#login'
  get '/report' => 'site#report'
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :image, EventImageUploader
end

app/models/nom.rb
class Nom < ActiveRecord::Base
  belongs_to :restaurant
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, NomPhotoUploader
  belongs_to :nom

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :logo, RestaurantLogoUploader

  has_many :noms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      respond_to do |format|
        format.html {redirect_to events_path }
        format.json { render json: @event }
      end
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :all_day, :starts_at, :ends_at, :url, :color, :image)
  end

end

app/controllers/noms_controller.rb
class NomsController < ApplicationController
  before_action :set_restaurant
  before_action :set_nom, only: [:show, :edit, :update, :destroy]

  # GET /noms
  # GET /noms.json
  def index
    @noms = @restaurant.noms.page(params[:page]).per(5)
  end

  # GET /noms/1
  # GET /noms/1.json
  def show
  end

  # GET /noms/new
  def new
    @nom = Nom.new
  end

  # GET /noms/1/edit
  def edit
  end

  # POST /noms
  # POST /noms.json
  def create
    @nom = @restaurant.noms.build(nom_params)

    respond_to do |format|
      if @nom.save
        format.html { redirect_to root_path, notice: 'Nom was successfully created.' }
        format.json { render :show, status: :created, location: @nom }
      else
        format.html { render :new }
        format.json { render json: @nom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noms/1
  # PATCH/PUT /noms/1.json
  def update
    respond_to do |format|
      if @nom.update(nom_params)
        format.html { redirect_to @nom, notice: 'Nom was successfully updated.' }
        format.json { render :show, status: :ok, location: @nom }
      else
        format.html { render :edit }
        format.json { render json: @nom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noms/1
  # DELETE /noms/1.json
  def destroy
    @nom.destroy
    respond_to do |format|
      format.html { redirect_to noms_url, notice: 'Nom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_nom
      @nom = Nom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nom_params
      params.require(:nom).permit(:name, :delicious)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :get_the_nom

  def index
    @photos = @nom.photos
    @photo = @nom.photos.build
  end

  def create
    @photo = @nom.photos.build(photo_params)
    if @photo.save
      redirect_to nom_photos_path(@nom)
    else
      render :index
    end
  end

  private

  def get_the_nom
    @nom = Nom.find(params[:nom_id])
  end

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :logo)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @event = Event.new
  end

  def places
    respond_to do |format|
      format.html do
        render :index
      end
      format.json do
        render json: {name: 'Jeremy'}
      end
    end
  end

  def contact
    if request.post?
      NotificationMailer.contact_form(params).deliver
      redirect_to root_path
    end
  end

  def login
    #UserMailer.welcome('billy@test.com').deliver
    redirect_to root_path
  end

  def report
    AdminMailer.report.deliver
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/noms_helper.rb
module NomsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/events/_new_modal.html.erb
<div id="create-event" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="create-event-label" aria-hidden="true">
  <div class="modal-dialog">
    <%= form_for(@event) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h4>Create New Event</h4>
        </div>
        <div class="modal-body">
          <%= f.label(:title) %>
          <%= f.text_field(:title) %>
          <%= f.label(:all_day) %>
          <%= f.select(:all_day, [['Yes', true], ['Nope', false]]) %>
          <%= f.label(:starts_at) %>
          <%= f.datetime_select(:starts_at) %>
          <%= f.label(:ends_at) %>
          <%= f.datetime_select(:ends_at) %>
          <%= f.label(:url) %>
          <%= f.text_field(:url) %>
          <%= f.label(:color) %>
          <%= f.text_field(:color) %>
          <%= f.file_field(:image) %>
        </div>
        <div class="modal-footer">
          <a href="#" class="close btn btn-danger" data-dismiss="modal">Cancel</a>
          <%= f.submit('Save Event', class: 'btn btn-primary') %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
  <%= image_tag(event.image.url(:large)) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="container">
    <nav class="navbar navbar-default" role="navigation">
      <a class="navbar-brand" href="<%= root_path %>">The Noms Factory</a>
      <ul class="nav navbar-nav">
        <li>
          <a href="<%= restaurants_path %>">Restaurants</a>
        </li>
        <li>
          <a href="<%= events_path %>">Events</a>
        </li>
      </ul>
    </nav>
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </section>
</body>
</html>

app/views/noms/_form.html.erb
<%= form_for([@restaurant, @nom]) do |f| %>
  <% if @nom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nom.errors.count, "error") %> prohibited this nom from being saved:</h2>

      <ul>
      <% @nom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :delicious %><br>
    <%= f.check_box :delicious %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/noms/edit.html.erb
<h1>Editing nom</h1>

<%= render 'form' %>

<%= link_to 'Show', @nom %> |
<%= link_to 'Back', noms_path %>

app/views/noms/index.html.erb
<a href="<%= new_restaurant_nom_path(@restaurant.id) %>" class="btn btn-success btn-lg pull-right"><span class="fa fa-plus"></span> New Nom</a>
<h1 class="page-header">Listing noms</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Delicious</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noms.each do |nom| %>
      <tr>
        <td><%= nom.name %></td>
        <td><%= nom.delicious %></td>
        <td><%= link_to("View #{pluralize(nom.photos.count, 'Photo')}", nom_photos_path(nom.id)) %></td>
        <td><%= link_to 'Show', restaurant_nom_path(@restaurant.id, nom.id) %></td>
        <td><%= link_to 'Edit', edit_restaurant_nom_path(@restaurant.id, nom.id) %></td>
        <td><%= link_to content_tag(:i, '', class: 'fa fa-trash-o'), restaurant_nom_path(@restaurant.id, nom.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @noms %>
<%= page_entries_info @noms %>

<br>

app/views/noms/new.html.erb
<h1>New nom</h1>

<%= render 'form' %>

app/views/noms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nom.name %>
</p>

<p>
  <strong>Delicious:</strong>
  <%= @nom.delicious %>
</p>

<%= link_to 'Edit', edit_nom_path(@nom) %> |
<%= link_to 'Back', noms_path %>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

<%= form_for([@nom, @photo]) do |f| %>
  <%= f.label(:image, 'Upload Photo') %>
  <%= f.file_field(:image) %>
  <%= f.submit('Upload', class: 'btn btn-primary') %>
<% end %>

<div class="row">
  <% @photos.each do |photo| %>
    <% next if photo.image.blank? %>
    <div class="col-sm-3">
      <%= image_tag(photo.image.url(:big)) %>
    </div>
  <% end %>
</div>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label(:logo) %><br>
    <%= f.file_field(:logo) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Address</th>
      <th>Noms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= image_tag(restaurant.logo.url(:thumb)) %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to('View Noms', restaurant_noms_path(restaurant.id)) %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@restaurant.logo.url(:normal)) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/site/contact.html.erb
<h1>Contact Page</h1>
<p>Contact us and let us know what you think!</p>
<%= form_tag(contact_path) do %>
  <p>
    <%= label_tag(:user_email) %><br />
    <%= text_field_tag(:user_email) %>
  </p>
  <p>
    <%= label_tag(:in_regard_to) %><br />
    <%= text_field_tag(:in_regard_to) %>
  </p>
  <p>
    <%= label_tag(:content) %><br />
    <%= text_area_tag(:content) %>
  </p>
  <p>
    <%= submit_tag('Send Contact') %>
  </p>
<% end %>

app/views/site/index.html.erb
<h1>Welcome, dude!</h1>
<p>What do you think of my app?</p>
<a href="<%= report_path %>" class="btn btn-info">Send Report</a>

<a href="#hello" data-toggle="modal" class="btn btn-default">HELLO</a>
<a href="#create-event" data-toggle="modal" class="btn btn-success">Create Event</a>
<%= render('events/new_modal') %>
<div id="restaurants" class="pull-right">

</div>

<div id="calendar">

</div>



<div id="hello" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="hello-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Hello Modal</h4>
      </div>
      <div class="modal-body">
        <p>YO YO !</p>
      </div>
    </div>
  </div>
</div>